# Site settings
title: "Jeff Hilnbrand"
email: jahilnbrand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some description goes here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jhil.co" # the base hostname & protocol for your site

twitter_username:   jhilmd
facebook_username:  jhilnbrand
github_username:    jhil
dribbble_username:  jhil
linkedin_username:  jhilnbrand
medium_username:    jhilmd

# Build settings
markdown: kramdown
